module.exports.registrationSelectors = {
  firstNameInput: '#AccountFrm_firstname',
  lastNameInput: '#AccountFrm_lastname',
  emailInput: '#AccountFrm_email',
  addressInput: '#AccountFrm_address_1',
  cityInput: '#AccountFrm_city',
  countryIdSelect: '#AccountFrm_country_id',
  zoneIdSelect: '#AccountFrm_zone_id',
  postcodeInput: '#AccountFrm_postcode',
  loginnameInput: '#AccountFrm_loginname',
  passwordInput: '#AccountFrm_password',
  confirmPasswordInput: '#AccountFrm_confirm',
  agreementCheckboxLabel: 'I have read and agree to the',
  createAccountButton: 'Continue',
  successMessage: 'Your Account Has Been Created!',
  };